### ISSUE TITLE
Parts in unlockParts node

### ISSUE THREAD

**Issue by lordlimabean** [Its-Just-Luci/ROEngines-Extended#1]
Many late game engines default to unlockParts node. I found all of these in the unlockParts node that were in the ROenginesExtended folder: AMBER_NicheParts , ISE100_NicheParts , R42HiPAT , RD0162_RE , RD0169_RE , RS76_BDB , STBE_BDB , STBE3_BDB , TR-107_BDB , TR308_NicheParts , XLR132_SSTU , YF-77

**Comment by Its-Just-Luci** [comment]
noted. I will try to get on this asap, thanks for the heads up

**Comment by Its-Just-Luci** [comment]
ok, sorry it took so long, but it should all be in working condition
